### ISSUE TITLE
Request: prefix global functions.

### ISSUE THREAD

**Issue by TussendoorHQ** [BrianHenryIE/strauss#74]
The strauss package is working perfectly for prefixing classes and constants. So far it helps us avoiding dependency hell within our custom WordPress plugin and we prevented a lot of compatibility issues with other plugins.

But I'm running into an issue. The [illuminate\collections](https://packagist.org/packages/illuminate/collections) is being used and this package loads global functions in the helpers.php. Which is checking if a function exist like in this example:
```php
if (! function_exists('collect')) {
    /**
     * Create a collection from the given value.
     *
     * @param  mixed  $value
     * @return \Custom\Prefix\Illuminate\Support\Collection
     */
    function collect($value = null)
    {
        return new Collection($value);
    }
} 
```

But when a different plugin is using the same package and this plugin is loaded first; we end up in the global function of that plugin. Which is not using my custom prefixed package and which is not using the same version as we do in our plugin.

This is resulting in this error:
```
#0 /home/user/public_html/wp-content/plugins/reviewx/vendor/jouleslabs/warehouse/src/Supports/common.php(58): explode()
#1 /home/user/public_html/wp-content/plugins/reviewx/vendor/jouleslabs/warehouse/src/Supports/common.php(50): array_get()
#2 /home/user/public_html/wp-content/plugins/our-custom-plugin/vendor/illuminate/collections/Arr.php(459): data_get()
#3 /home/user/public_html/wp-content/plugins/our-custom-plugin/vendor/illuminate/collections/Collection.php(688): Custom\Prefix\Illuminate\Support\Arr::pluck()
```

This is my composer.json:
```json
{
    "name": "custom/plugin",
    "license": "GPL-2.0-or-later",
    "description": "WordPress plugin developed by Tussendoor.",
    "type": "wordpress-plugin",
    "require": {
        "php": "^8.0",
        "nesbot/carbon": "^2.66.0",
        "illuminate/database": "^8.0.0",
        "twbs/bootstrap": "^5.2.3",
        "fortawesome/font-awesome": "^6.4.0",
        "adbario/php-dot-notation": "^3.3.0",
        "woocommerce/action-scheduler": "^3.4.0",
        "yahnis-elsts/plugin-update-checker": "^4.13"
    },
    "autoload": {
        "psr-4": {
            "Custom\\Namespace\\": "app/"
        },
        "files": [
            "vendor/woocommerce/action-scheduler/action-scheduler.php"
        ],
        "classmap": [
            "vendor"
        ]
    },
    "config": {
        "optimize-autoloader": true,
        "sort-packages": true,
        "platform": {
            "php": "8.0.3"
        }
    },
    "scripts": {
        "pre-update-cmd": [
            "sh strauss-observer.sh"
        ],
        "post-install-cmd": [
            "sh strauss-prefixer.sh"
        ],
        "post-update-cmd": [
            "sh strauss-prefixer.sh"
        ]
    },
    "extra": {
        "strauss": {
            "target_directory": "vendor",
            "namespace_prefix": "Custom\\Prefix\\",
            "constant_prefix": "TSD_CUSTOM_PREFIX_",
            "include_modified_date": false,
            "include_author": false,
            "delete_vendor_packages": true,
            "exclude_from_prefix": {
                "packages": [
                    "yahnis-elsts/plugin-update-checker",
                    "woocommerce/action-scheduler"
                ]
            },
            "override_autoload": {
                "nesbot/carbon": {
                    "autoload": {
                        "psr-4": {
                            "Carbon\\": "src/Carbon/"
                        }
                    },
                    "classmap": [
                        "lazy"
                    ]
                }
            }
        }
    }
}
```

I'm using the strauss.phar at the moment. Is there a way to support prefixing global functions?

**Comment by BrianHenryIE** [comment]
That is written now but needs testing before I can merge it confidently.

https://github.com/brianhenryie/strauss/compare/master...BrianHenryIE:strauss:add-global-namespace-to-named-namespace-command?expand=1

**Comment by BrianHenryIE** [comment]
Complete in [0.21.0](https://github.com/BrianHenryIE/strauss/releases/tag/0.21.0)
